use chow_db;

insert into FoodCategories(category_name, created_at, updated_at) values('Afghan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('African', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('American (New)', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('American (Traditional)', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Arabian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Argentine', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Armenian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Asian Fusion', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Australian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Austrian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Bangladeshi', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Basque', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Belgian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Brasseries', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Brazilian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('British', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Bulgarian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Burmese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cajun/Creole', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cambodian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Caribbean', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Catalan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Chinese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cuban', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Czech', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Ethiopian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Filipino', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('French', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Georgian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('German', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Greek', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Guamanian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Hawaiian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Himalayan/Nepalese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Honduran', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Hong Kong Style Cafe', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Hungarian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Iberian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Indian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Indonesian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Irish', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Italian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Japanese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Kebab', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Korean', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Laotian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Latin American', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Malaysian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Mediterranean', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Mexican', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Middle Eastern', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Modern European', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Mongolian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Moroccan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('New Mexican Cuisine', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Nicaraguan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Pakistani', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Pan Asian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Persian/Iranian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Peruvian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Polish', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Polynesian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Portuguese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Poutineries', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Russian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Scandinavian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Scottish', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Singaporean', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Slovakian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Spanish', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Sri Lankan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Steakhouses', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Syrian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Taiwanese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Tex-Mex', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Thai', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Turkish', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Ukrainian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Uzbek', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Vietnamese', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Barbeque', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Breakfast & Brunch', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Buffets', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Burgers', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cafes', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cafeteria', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Cheesesteaks', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Chicken Shop', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Chicken Wings', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Comfort Food', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Creperies', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Delis', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Diners', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Dinner Theater', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Fast Food', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Fish & Chips', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Fondue', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Food Court', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Food Stands', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Game Meat', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Gastropubs', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Gluten-Free', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Halal', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Hot Dogs', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Hot Pot', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Kosher', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Live/Raw Food', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Noodles', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Pizza', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Pop-Up Restaurants', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Salad', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Sandwiches', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Seafood', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Soul Food', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Soup', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Southern', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Supper Clubs', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Sushi Bars', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Tapas Bars', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Tapas/Small Plates', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Vegan', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Vegetarian', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Waffles', now(), now());
insert into FoodCategories(category_name, created_at, updated_at) values('Wraps', now(), now());