use chow_db;

insert into food_category(category_name) values('Afghan');
insert into food_category(category_name) values('African');
insert into food_category(category_name) values('American (New)');
insert into food_category(category_name) values('American (Traditional)');
insert into food_category(category_name) values('Arabian');
insert into food_category(category_name) values('Argentine');
insert into food_category(category_name) values('Armenian');
insert into food_category(category_name) values('Asian Fusion');
insert into food_category(category_name) values('Australian');
insert into food_category(category_name) values('Austrian');
insert into food_category(category_name) values('Bangladeshi');
insert into food_category(category_name) values('Basque');
insert into food_category(category_name) values('Belgian');
insert into food_category(category_name) values('Brasseries');
insert into food_category(category_name) values('Brazilian');
insert into food_category(category_name) values('British');
insert into food_category(category_name) values('Bulgarian');
insert into food_category(category_name) values('Burmese');
insert into food_category(category_name) values('Cajun/Creole');
insert into food_category(category_name) values('Cambodian');
insert into food_category(category_name) values('Caribbean');
insert into food_category(category_name) values('Catalan');
insert into food_category(category_name) values('Chinese');
insert into food_category(category_name) values('Cuban');
insert into food_category(category_name) values('Czech');
insert into food_category(category_name) values('Ethiopian');
insert into food_category(category_name) values('Filipino');
insert into food_category(category_name) values('French');
insert into food_category(category_name) values('Georgian');
insert into food_category(category_name) values('German');
insert into food_category(category_name) values('Greek');
insert into food_category(category_name) values('Guamanian');
insert into food_category(category_name) values('Hawaiian');
insert into food_category(category_name) values('Himalayan/Nepalese');
insert into food_category(category_name) values('Honduran');
insert into food_category(category_name) values('Hong Kong Style Cafe');
insert into food_category(category_name) values('Hungarian');
insert into food_category(category_name) values('Iberian');
insert into food_category(category_name) values('Indian');
insert into food_category(category_name) values('Indonesian');
insert into food_category(category_name) values('Irish');
insert into food_category(category_name) values('Italian');
insert into food_category(category_name) values('Japanese');
insert into food_category(category_name) values('Kebab');
insert into food_category(category_name) values('Korean');
insert into food_category(category_name) values('Laotian');
insert into food_category(category_name) values('Latin American');
insert into food_category(category_name) values('Malaysian');
insert into food_category(category_name) values('Mediterranean');
insert into food_category(category_name) values('Mexican');
insert into food_category(category_name) values('Middle Eastern');
insert into food_category(category_name) values('Modern European');
insert into food_category(category_name) values('Mongolian');
insert into food_category(category_name) values('Moroccan');
insert into food_category(category_name) values('New Mexican Cuisine');
insert into food_category(category_name) values('Nicaraguan');
insert into food_category(category_name) values('Pakistani');
insert into food_category(category_name) values('Pan Asian');
insert into food_category(category_name) values('Persian/Iranian');
insert into food_category(category_name) values('Peruvian');
insert into food_category(category_name) values('Polish');
insert into food_category(category_name) values('Polynesian');
insert into food_category(category_name) values('Portuguese');
insert into food_category(category_name) values('Poutineries');
insert into food_category(category_name) values('Russian');
insert into food_category(category_name) values('Scandinavian');
insert into food_category(category_name) values('Scottish');
insert into food_category(category_name) values('Singaporean');
insert into food_category(category_name) values('Slovakian');
insert into food_category(category_name) values('Spanish');
insert into food_category(category_name) values('Sri Lankan');
insert into food_category(category_name) values('Steakhouses');
insert into food_category(category_name) values('Syrian');
insert into food_category(category_name) values('Taiwanese');
insert into food_category(category_name) values('Tex-Mex');
insert into food_category(category_name) values('Thai');
insert into food_category(category_name) values('Turkish');
insert into food_category(category_name) values('Ukrainian');
insert into food_category(category_name) values('Uzbek');
insert into food_category(category_name) values('Vietnamese');
insert into food_category(category_name) values('Barbeque');
insert into food_category(category_name) values('Breakfast & Brunch');
insert into food_category(category_name) values('Buffets');
insert into food_category(category_name) values('Burgers');
insert into food_category(category_name) values('Cafes');
insert into food_category(category_name) values('Cafeteria');
insert into food_category(category_name) values('Cheesesteaks');
insert into food_category(category_name) values('Chicken Shop');
insert into food_category(category_name) values('Chicken Wings');
insert into food_category(category_name) values('Comfort Food');
insert into food_category(category_name) values('Creperies');
insert into food_category(category_name) values('Delis');
insert into food_category(category_name) values('Diners');
insert into food_category(category_name) values('Dinner Theater');
insert into food_category(category_name) values('Fast Food');
insert into food_category(category_name) values('Fish & Chips');
insert into food_category(category_name) values('Fondue');
insert into food_category(category_name) values('Food Court');
insert into food_category(category_name) values('Food Stands');
insert into food_category(category_name) values('Game Meat');
insert into food_category(category_name) values('Gastropubs');
insert into food_category(category_name) values('Gluten-Free');
insert into food_category(category_name) values('Halal');
insert into food_category(category_name) values('Hot Dogs');
insert into food_category(category_name) values('Hot Pot');
insert into food_category(category_name) values('Kosher');
insert into food_category(category_name) values('Live/Raw Food');
insert into food_category(category_name) values('Noodles');
insert into food_category(category_name) values('Pizza');
insert into food_category(category_name) values('Pop-Up Restaurants');
insert into food_category(category_name) values('Salad');
insert into food_category(category_name) values('Sandwiches');
insert into food_category(category_name) values('Seafood');
insert into food_category(category_name) values('Soul Food');
insert into food_category(category_name) values('Soup');
insert into food_category(category_name) values('Southern');
insert into food_category(category_name) values('Supper Clubs');
insert into food_category(category_name) values('Sushi Bars');
insert into food_category(category_name) values('Tapas Bars');
insert into food_category(category_name) values('Tapas/Small Plates');
insert into food_category(category_name) values('Vegan');
insert into food_category(category_name) values('Vegetarian');
insert into food_category(category_name) values('Waffles');
insert into food_category(category_name) values('Wraps');